# Generated by Django 4.2.20 on 2025-05-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booker_comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_verification_pic',
            field=models.ImageField(blank=True, null=True, upload_to='return_verifications/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'BOOKED'), ('PICKED UP', 'PICKED UP'), ('OVERDUE', 'OVERDUE'), ('RETURNED UNVERIFIED', 'RETURNED UNVERIFIED'), ('RETURNED VERIFIED', 'RETURNED VERIFIED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('event', 'Event & Party'), ('games', 'Board Games'), ('stationery', 'Stationery'), ('photo', 'Photography & Video'), ('tech', 'Electronics & Tech'), ('arts', 'Arts & Craft'), ('catering', 'Catering'), ('tools', 'Tools & DIY'), ('misc', 'Miscellaneous')], max_length=50),
        ),
    ]
